### PR TITLE
Bootstrapping issues

### PR DESCRIPTION
**Pull request by balboah**
Great example for how to get nghttpx working. I've made some small changes that I struggled on while following the README as well as tweaking the example deployment configurations.

Also what do you think about trying to get [Let's encrypt](https://letsencrypt.org) working with for example [kube-lego](https://github.com/jetstack/kube-lego) like the nginx ingress is doing?

@tatsuhiro-t

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR.  We will look into it.
As for kube-lego, I'm not sure what is the requirement for ingress controller.  If kube-lego can obtain certificates from let's encrypt without interacting ingress controller, then we don't have to do anything.  nghttpx ingress controller watches Ingress and associated TLS Secret resources, and any changes will make ingress controller reload its configuration.

**Comment by tatsuhiro-t** [comment]
@balboah To proceed to merge this PR, please read our [CLA](https://zlabjp.github.io/cla/).  If you accept it, please say so in this thread.  Thank you.

**Comment by balboah** [comment]
@tatsuhiro-t I accept to the CLA for this PR and any further PR's submitted by me

**Comment by tatsuhiro-t** [comment]
Thank you.  PR looks good.  Will merge soon.

**Pull request merged**
