### PR TITLE
Upgrade to nghttp2 v1.26.0

### PR DESCRIPTION
**Pull request by weitzj**
There is a new release available.
Fixes: https://github.com/zlabjp/nghttpx-ingress-lb/issues/58
See: https://github.com/nghttp2/nghttp2/releases

### CODE REVIEW

**Comment by weitzj** [comment]
@tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
Thank you for PR.
To proceed to merge this PR, please read our [CLA](https://zlabjp.github.io/cla/).  If you accept it, please say so in this thread.  Thank you.

**Comment by weitzj** [comment]
I accept your CLA

**Comment by tatsuhiro-t** [comment]
Thank you!

**Pull request merged**
